name: m_cubit
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  logger: ^2.6.2
  collection: ^1.19.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

